CMAKE_MINIMUM_REQUIRED(VERSION 3.5)

IF(NOT KK_DATA_STRUCTS_DIR)
	MESSAGE(FATAL_ERROR "KK_DATA_STRUCTS_DIR not specified")
ENDIF()

FILE(GLOB KKDataStructures_SOURCES ${KK_DATA_STRUCTS_DIR}/*.c)
SET(KKDataStructures_INCLUDE_DIR ${KK_DATA_STRUCTS_DIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(KKDataStructures DEFAULT_MSG KKDataStructures_INCLUDE_DIR KKDataStructures_SOURCES)
