CMAKE_MINIMUM_REQUIRED(VERSION 3.5)

IF(NOT JSMN_DIR)
	MESSAGE(FATAL_ERROR "JSMN_DIR not specified")
ENDIF()

FILE(GLOB JSMN_SOURCES ${JSMN_DIR}/*.c)
FILE(GLOB JSMN_INCLUDE_DIRS ${JSMN_DIR})
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(JSMN DEFAULT_MSG JSMN_INCLUDE_DIRS JSMN_SOURCES)
