SET(NSSU_SRC_FILES
	nss_uart.c
)

SET(NSSU_HEADERS
	nss_uart.h
)

FIND_PATH(NSSU_INC_DIR ${NSSU_HEADERS}
	PATH_SUFFIXES NotSoSoftUart
	HINTS ${CMAKE_SOURCE_DIR}/drv
	CMAKE_FIND_ROOT_PATH_BOTH
)

FIND_FILE(NSSU_SOURCES ${NSSU_SRC_FILES}
	PATH_SUFFIXES NotSoSoftUart
	HINTS ${CMAKE_SOURCE_DIR}/drv
	CMAKE_FIND_ROOT_PATH_BOTH
)

SET(NotSoSoftUart_INCLUDE_DIRS ${NSSU_INC_DIR})
SET(NotSoSoftUart_SOURCES ${NSSU_SOURCES})

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(NotSoSoftUart DEFAULT_MSG NotSoSoftUart_INCLUDE_DIRS NotSoSoftUart_SOURCES)

