SET(MINUNIT_INC_DIR ${CMAKE_SOURCE_DIR}/tests/minunit)

FILE(GLOB TEST_COMMON_SOURCES ${CMAKE_SOURCE_DIR}/tests/*.c) 

SET(TEST_INCLUDE_DIRS ${MINUNIT_INC_DIR})
SET(TEST_SOURCES ${TEST_COMMON_SOURCES})
